<?php include 'inc/app.php'; ?>
<!-- css starts here -->
<link rel="stylesheet" href="css/terms.css">
<!-- css ends here -->
<!-- page Header starts here -->
<section class="pageHeader-sec">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-header-wrapper">
                    <div class="heading-wrapper">
                        <h3>Hasla Futures Services Agreement</h3>
                    </div>
                    <div class="breadcrumbs-wrapper">
                        <ul>
                            <li class="base-page"><a href="#">HOME</a></li>
                            <li class="arrow"><a href="#"><i class="fa fa-angle-right"></i></a></li>
                            <li class="current-page"><a href="#">Hasla Futures Services Agreement</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- page Header ends here -->
<!--Privacy Policy -->
<section class="privacy-sec">
    <div class="container">
        <div class="privacy-head">
            <h2>Hasla Futures Services Agreement</h2>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="privacy-stuff for-line">
                    <p>This Hasla Futures Services Agreement (this “Agreement”) shall apply to all Futures Accounts (as defined below) opened and maintained with Hasla as well as all Futures (as defined below) trading services provided by Hasla to you. If any Futures Account is opened or maintained subject to some other terms, then this Agreement is in addition to those other terms.</p>
                    <p>All terms and references used in this Agreement and which are defined and construed in the Hasla Terms of Use (the “Terms of Use”) but are not defined or construed in this Agreement shall have the same meaning and construction in the terms of this Agreement.</p>
                    <p>The terms in this Agreement are to be read together with the Terms of Use. In the event of any conflict or inconsistency between the terms in this Agreement and the Terms of Use, the terms in this Agreement shall prevail.</p>
                </div>
                <div class="privacy-stuff">
                    <h3>1. Definitions and Interpretation</h3>
                    <p>1.1. The following definitions are applicable to the terms of this Agreement:</p>
                    <p>“Applicable Law” means all relevant or applicable statutes, laws, rules, regulations, notices, orders, bye-laws, rulings, directives, circulars, guidelines, practice notes and interpretations (whether of a governmental body, regulatory or other authority, or self-regulatory organisation in relation to which Hasla is a member, or Hasla or a relevant Hasla Account, service, Futures Account or Transaction is subject to, or otherwise).</p>
                    <p>“COIN-M Futures” means futures contracts that use Digital Assets and/or Digital Currencies (other than stablecoins) as prescribed by Hasla in its sole discretion as a collateral, and shall not include USDS-M Futures (as defined below).</p>
                    <p>“Confirmation” means the written notice (including telex, facsimile or other electronic means from which it is possible to produce a hard copy) which contains the specific terms of a Transaction entered into between you and Hasla.</p>
                    <p>“Collateral” in respect of the Cross Collateral Services (as defined below), means any Digital Assets and/or Digital Currencies deposited with or held by Hasla as security or credit support in a Futures Account for any Transactions or your obligations under this Agreement.</p>
                    <p>“Cross Collateral Loan” is as defined in Clause 6.14.</p>
                    <p>“Cross Collateral Services” means the optional service provided by Hasla to you as part of the Futures trading services in which you may collateralize your Digital Assets (in a Digital Currency of Hasla ’s sole discretion) to borrow Tether (USDT) or other Digital Currencies that Hasla may from time to time prescribe in its sole discretion.</p>
                    <p>“Futures” means COIN-M Futures, USDS-M Futures or any other futures contracts that Hasla may allow at its sole discretion to be traded on its Electronic Facilities (as defined below).</p>
                    <p>“Futures Account” means an account maintained or to be maintained by Hasla for you for the sole purpose of the Futures trading services provided by Hasla to you.</p>
                    <p>“Electronic Facility” means any electronic broking, trading, clearing or other services, systems or platforms and/or related software and technology that are made available to you by or through Hasla whether under this Agreement, the Terms of Use or otherwise.</p>
                    <p>“Initial Margin” in respect of a Transaction, shall be the minimum amount of Margin that Hasla may from time to time in its sole discretion determine to be deposited in a Futures Account in order to open a leveraged position in respect of that Transaction.</p>
                    <p>“Liquidation Level” means the LTV Ratio (in the case of Cross Collateral Services) or the level (in the case of Futures trading services in general) as prescribed by Hasla from time to time in the Futures Trading Rules (as defined below) which will result in Hasla selling or disposing of any or all Collateral (in the case of Cross Collateral Services) or Margin (in the case of Futures trading services in general) in the applicable Futures Account(s) to satisfy the LTV Ratio or margin requirements (as the case may be).</p>
                    <p>“Liquidation Price” means the Mark Price at which Liquidation (as defined below) occurs. For the avoidance of doubt, the Liquidation Price as quoted by Hasla on its website or mobile application is for reference only and shall not be binding on Hasla.</p>
                    <p>“Loan-to-Value Ratio” or “LTV Ratio” in respect of the Cross Collateral Services, means the percentage of the total amount of the Cross Collateral Loan divided over the sum of the total value of the Collateral.</p>
                    <p>“Loss” means any and all loss, damage, costs, charges and/or expenses of whatsoever nature and howsoever arising, including without limitation legal fees on a full indemnity basis, cost of funding and loss or cost incurred as a result of the terminating, liquidating or re-establishing of any hedge or related trading position, loss of profit, loss of revenue, loss of opportunity, consequential, unforeseeable, special or indirect damages or expenses.</p>
                    <p>“Maintenance Margin” in respect of a Transaction, shall be the amount of Margin that Hasla may from time to time in its sole discretion determine to be required to keep the relevant leveraged position in respect of the applicable Transactions open.</p>
                    <p>“Manifest Error” means any error, omission or misquote (whether an error of Hasla or any third party) which is manifest or palpable, including a misquote by any representative of Hasla taking into account the current market and currently advertised quotes, or any error or lack of clarity of any information, source, commentator, official, official result or pronunciation. The fact that you may have entered into, or refrained from entering into, a corresponding financial commitment, contract or trade in reliance on a Transaction entered into with Binance (or that you have suffered or may suffer any loss whether direct, indirect, consequential or otherwise) is deemed irrelevant as a factor and shall not be taken into account in determining whether a situation amounts to a Manifest Error.</p>
                    <p>“Margin” in respect of Futures trading services, means any Digital Assets and/or Digital Currencies deposited with or held by Hasla as security or credit support in a Futures Account for any Transactions or your obligations under this Agreement.</p>
                    <p>“Margin Call” means the request issued by Hasla to you, to top up any shortfall of Collateral or Margin (as the case may be) in the Futures Account.</p>
                    <p>“Mark Price” in respect of COIN-M Futures or USDS-M Futures, means the fair value of the relevant Futures regardless whether that Futures is a perpetual futures or quarterly futures and which is detailed in the relevant Futures Trading Rules in respect of COIN-M Futures (HERE) and the Futures Trading Rules in respect of USDS-M Futures (HERE).</p>
                    <p>“Order” means any offer to enter into a Transaction, or any of your instruction, request, application or order (in whatever form (including without limitation limit orders, market orders, stop limit orders, stop market orders, take profit limit orders, take profit market orders, trailing stop orders, post only orders, and limit take profit or stop loss orders) (HERE) and howsoever sent, given or transmitted) to Binance or which Binance reasonably believes to be your instruction, request, application or order and includes any instruction, request or order to revoke, ignore or vary any previous request or order.</p>
                    <p>“Transaction” means any transactions in respect of Futures as Hasla may from time to time permit to be carried out under a Futures Account.</p>
                    <p>“USDS-M Futures” means futures contracts that use Tether (USDT), Hasla USD (HUSD) and/or any other stablecoins that Hasla may determine from time to time as a collateral, and shall not include COIN-M Futures.</p>
                    <p>1.2. The headings are inserted for convenience only and shall not affect the construction of this Agreement. Expressions in the singular form shall include the plural and vice versa, and all references to the masculine genders shall include the female and neuter genders and vice versa.</p>
                    <p>1.3. The words “include” or “including” shall be deemed to be followed by “without limitation” or “but not limited to” whether or not they are followed by such phrases or words of like import, and “otherwise” shall not be construed as limited by words with which it is associated.</p>
                    <h3>2. Futures Trading Rules</h3>
                    <p>By accessing your Futures Account, you agree to be bound by the rules in relation to the Futures trading services provided by Hasla to you including without limitation:</p>
                    <p>(a) the trading rules of COIN-M Futures and USDS-M Futures (HERE)</p>
                    <p>(b) the provisions regarding leverage and margin of USDS-M Futures (HERE)</p>
                    <p>(c) the provisions regarding leverage and margin of COIN-M Futures (HERE)</p>
                    <p>(d) the provisions regarding funding rates (HERE)</p>
                    <p>(e) the provisions regarding Liquidation (HERE)</p>
                    <p>(f) the fee schedules of the trading fees site (HERE)</p>
                    <p>(g) other rules and regulations that Hasla may from time to time in its sole and absolute discretion determine (HERE) to form part of this Agreement) which shall form part of this Agreement (collectively, the “Futures Trading Rules”).</p>
                    <h3>3. Futures Orders</h3>
                    <p>3.1. To enter in to or close or otherwise carry out a Transaction, you may do so by placing a relevant Order with Hasla through the use of any Electronic Facility as Hasla may approve in its sole discretion.</p>
                    <p>3.2. In the event that Hasla assumes the role of the counterparty to any Transaction, Hasla shall be entitled to all gains, profits and benefits derived from such Transaction.</p>
                    <p>3.3. Nothing in this Agreement obliges Hasla to enter into any Transaction with you, and Hasla may refuse to enter into any Transaction, accept or otherwise act on any Order without giving any reason or any notice to you. Hasla shall be entitled (but not obliged) to verify and be satisfied with respect to the identity of the person purporting to give such Order or the source and origin of such Order and Hasla may rely or act upon any such Order unless and until Hasla is satisfied as to the matters on which Hasla sought verification.</p>
                    <p>3.4. Where any Order is ambiguous or inconsistent with any other Order, Hasla shall be entitled to rely and act upon any Order in accordance with any reasonable interpretation thereof which Hasla believes in good faith to be the correct interpretation.</p>
                    <p>3.5. Hasla shall only act on Order in respect of any Hasla Account and Futures Account or any part of the Digital Assets and Digital Currencies held in such accounts. Hasla shall not be required to act in accordance with any Order which purports to dispose of or deal with any Digital Assets and/or Digital Currencies which are in fact not held in any Hasla Account and/or Futures Account.</p>
                    <p>3.6. Hasla shall bear no Loss and/or liability whatsoever for failing to comply with any of your Order or for exercising or failing to exercise any discretion, power or authority conferred upon Hasla by this Agreement. Hasla shall not be liable to you for any and all Loss incurred by you arising from any loss or delay in the transmission or wrongful interception of any Order through any equipment or system, including any equipment or system owned and/or operated by or for Hasla.</p>
                    <p>3.7. You acknowledge and consent to the right of Hasla to aggregate your Orders with the orders of Hasla ’s other clients (whether for execution on other jurisdictions or otherwise). The allotment or distribution of any Digital Assets and/or Digital Currencies pursuant to such order aggregation to or amongst you and Hasla ’s other clients shall be at Hasla ’s sole and absolute discretion, and Hasla may also effect such Transactions as principal to the counterparty in such jurisdiction. If Hasla so acts, Hasla may also take such actions as Hasla may require in order to avoid liability to its counterparty.</p>
                    <h3>4. Margin</h3>
                    <p>4.1. You shall deposit, maintain in your Futures Account and/or otherwise provide Hasla with Margin in such form and amounts, at such times and in respect of such Futures Account as Hasla ance may from time to time in its sole and absolute discretion require, whether or not such requirement of Hasla is identical to or reflects or is greater than an applicable collateral requirements of any governmental body or self-regulatory organisation in any jurisdiction (including any exchange) which is required to be maintained by Hasla and/or you.</p>
                    <p>4.2. A list of Digital Assets and Digital Currencies approved by Hasla to be eligible as Margin will be prescribed by Hasla and certain Digital Assets and Digital Currencies may only be valued as Margin on a discounted basis. Hasla may (but shall not be obliged to) notify you of any changes to the list of eligible Digital Assets and Digital Currencies or discounts applied to the valuation thereof prior to those changes taking effect. Such notice shall indicate the effective date for those changes.</p>
                    <p>4.3. The value of any Margin shall be as determined by Hasla in its sole and absolute discretion.</p>
                    <p>4.4. Where applicable, you acknowledge and agree that separate Margin shall be provided by you in respect of each position as Hasla may require, and that the Margin in respect of each position shall be treated as separate for the purposes of this Agreement. Upon specific instructions provided by you, Hasla may (but is not obliged to) transfer all or part of the Margin held by Hasla for you in respect of any Futures Account to any other Hasla Account or to utilise such Margin for any purposes as required by you.</p>
                    <p>4.5. Hasla may establish margin requirements in respect of its margin trading services and such margin requirements will be set out in the Futures Trading Rules. Hasla may, in its sole and absolute discretion, with or without notice to you, vary the margin requirements for any Futures Account at any time and by any level, and may also stipulate that such margin requirements shall apply to existing positions as well as new positions in the Transactions affected by such change. Any written notice from Hasla stating that any such circumstance has arisen shall be deemed to be a conclusive determination of that event. You acknowledge that Binance may, in certain market conditions, effect an immediate change in Margin limits or levels and/or require additional Margin to be deposited immediately or within a specified period of time which may be less than 24 hours, and waives any right to object on the grounds that such requirement is unreasonable. No previous margin requirements shall set a precedent or bind Hasla.</p>
                    <p>4.6. If Hasla determines that additional Margin is required, you shall deposit with Hasla such additional Margin immediately upon demand, provided that, notwithstanding any such demand for additional Margin, Hasla may at any time exercise its rights under Clause 8 (Default and Termination). In making such determination in respect of the Margin provided for any Futures Account, Hasla shall not be required to take into consideration Margin held by Binance for you in respect of any other Futures Account.</p>
                    <p>4.7. You acknowledge that Margin may be held and used to secure the performance of your obligations as well as for such other purposes as the Applicable Laws may permit or stipulate for the Transactions traded.</p>
                    <p>4.8. All Margin shall be held by Hasla, notwithstanding any provision or instructions to the contrary, as continuing security and shall be subject to a general lien and right of set off in favour of Hasla for any and all of your obligations, liabilities or monies whatsoever at any time now or hereafter owing, due, incurred or payable by you to Hasla under this Agreement or otherwise, whether present or future, actual or contingent, solely or jointly or whether as principal or surety, and Hasla may realise any of your Margin as provided for in this Agreement.</p>
                    <p>4.9. Hasla shall be entitled to deposit, pledge, repledge, hypothecate, re-hypothecate, invest or loan any Margin in whatever form provided by Hasla or otherwise, and shall not be under any obligation to notify you of the same nor account to you for any interest, income or benefit that may be derived therefrom. No interest shall be paid on any type of Margin deposited by you with Hasla and you acknowledge and agree that interest earned on the Margin deposited under this Agreement may be retained by Hasla for its own account and benefit. Hasla shall at no time be required to deliver to you the identical property delivered to or purchased by Hasla as Margin for the Futures Account but only property of substantially the same kind and amount, subject to adjustments for quantity and quality variations at the market price prevailing at the time of such delivery. Hasla shall not be liable to you for the loss of any Margin resulting directly or indirectly from the closure, bankruptcy, insolvency, liquidation, receivership or other events of a similar nature of any broker, market association, or body with which the Margin is deposited or pledged.</p>
                    <p>4.10. You shall at your own cost and at Hasla ’s request, execute and do all such deeds, acts and things (including without limitation, the performance of such further acts or the execution and delivery of any additional instruments or documents) as Hasla may require for the purposes of this Agreement, including but not limited to perfecting Hasla ’s rights to the Margin provided by you.</p>
                    <p>4.11. Hasla may deposit in Hasla ’s general account or any other account, any of your Margin and may commingle such Margin with the Digital Currency, Digital Assets, currencies and properties of Hasla ance or of some other person(s).</p>
                    <p>4.12. All Margin shall be held subject to Hasla ’s general rights in respect of your Digital Currencies and Digital Assets.</p>
                    <h3>5. Margin Level, Margin Call and Liquidation</h3>
                    <p>5.1. Without prejudice to the generality of this Clause 5 of this Agreement, unless otherwise directed by Hasla :</p>
                    <p>(a) You agree to place the required Initial Margin with Hasla before entering into any Transaction;</p>
                    <p>(b) You agree to maintain sufficient Maintenance Margin at all times for its outstanding Transactions. If the Margin falls below the required Maintenance Margin, you agree to transfer additional Margin to Hasla whether or not a Margin Call has been made by Hasla to restore to the required Initial Margin for the outstanding Transactions;</p>
                    <p>(c) You acknowledge that we calculate the profit and loss of your open positions in the Futures based on a proprietary model and that Hasla has the sole discretion to choose and amend the specification of the such proprietary model in order to reflect Hasla ’s view of the fair market price of the Futures;</p>
                    <p>(d) You acknowledge that if the margin requirements falls below the Liquidation Level such that the value of the Mark Price equals the value of the Liquidation Price, Hasla may and shall be fully entitled (but shall not be obliged) to sell or dispose of any or all Margins in your Futures Account in order to satisfy the margin requirements prescribed by Hasla for compliance by you, whether or not a Margin Call has been made (“Liquidation”), and Hasla is not required to provide notice before commencing Liquidation.</p>
                    <p>(e) You acknowledge and agree that it is your principal responsibility to monitor the margin requirements (including the Initial Margin, Maintenance Margin, the Mark Price and the Liquidation Price) in and for your Futures Account. All open positions of the Futures Account shall be marked-to-market daily, or at more frequent intervals as Hasla may determine in its sole discretion;</p>
                    <p>(f) Any Margin Call made by Hasla must be met by you by transferring additional Margin from your Hasla Account(s).</p>
                    <p>5.2. As Digital Asset markets are open 24 hours a day, 7 days a week, Margin Calls and liquidations may occur at any time, including outside of normal business hours. You further agree and acknowledge that the prices of Digital Assets are volatile and thus may decline speedily in value.</p>
                    <p>5.3. You acknowledge and agree that Hasla may (but shall not be obliged to) make Margin Calls on you in respect of any of your Futures Account orally or in writing or in such other manner as Hasla may in its sole and absolute discretion deem appropriate. Without prejudice to the generality of the foregoing, you acknowledge and agree that Hasla may contact you via telephone or email at any of the telephone number or email address provided by you to Hasla for the purposes of any Margin Calls and you shall make yourself available at such telephone numbers or email. If Hasla fails to reach you at any such telephone numbers or email, you shall be deemed to have defaulted on the Margin Call and Hasla may at any time exercise its rights set out in Clause 8 (Default and Termination). For the avoidance of doubt, Hasla shall be entitled (but not obliged) to make Margin Calls on you in respect of any of your Futures Account.</p>
                    <p>5.4. Failure of Hasla to exercise any or all of its rights under this Clause 5 shall not constitute a waiver of its rights to do so at any time thereafter, nor shall Hasla be subject to any liability to you for its acts or its failure to so act.</p>
                    <h3>6. Cross Collateral Services</h3>
                    <p>6.1. The Cross Collateral Services is a service provided by Hasla to you which allows you to use held Digital Assets as collateral in order to borrow Tether (USDT) as margin to participate in Futures trading. Notwithstanding the representations, warranties, agreements and undertakings at Clause 10 which shall apply to your access and use of the Cross Collateral Services, by accessing and using the Cross Collateral Services, you acknowledge and agree that you fully understand the risk associated with the Cross Collateral Services and that you shall access and use the Cross Collateral Services at your own risk. This Clause 6 shall apply to your access and use of the Cross Collateral Services. Collateral</p>
                    <p>6.2. You shall deposit, maintain in your Futures Account(s) and/or otherwise provide Hasla with Collateral in such form and amounts, at such times and in respect of such Futures Account as Hasla may from time to time in its sole and absolute discretion require, whether or not such requirement of Hasla is identical to or reflects or is greater than an applicable collateral requirements of any governmental body or self-regulatory organisation in any jurisdiction (including any exchange) which is required to be maintained by Hasla and/or you.</p>
                    <p>6.3. A list of Digital Assets and Digital Currencies approved by Hasla to be eligible as Collateral will be prescribed by Hasla and certain Digital Assets and Digital Currencies may only be valued as Collateral on a discounted basis. Hasla may (but shall not be obliged to) notify you of any changes to the list of eligible Digital Assets and Digital Currencies or discounts applied to the valuation thereof prior to those changes taking effect. Such notice shall indicate the effective date for those changes.</p>
                    <p>6.4. The value of any Collateral shall be as determined by Hasla in its sole and absolute discretion.</p>
                    <p>6.5. Upon specific instructions provided by you, Hasla may (but is not obliged to) transfer all or part of the Collateral held by Hasla for you in respect of any Futures Account to any other Hasla Account or to utilise such Collateral for any purposes as required by you.</p>
                    <p>6.6. Hasla may establish LTV Ratio requirements in respect of its Cross Collateral Services and such requirements (including LTV Ratio) will be set out in the Futures Trading Rules. Hasla may, in its sole and absolute discretion, with or without notice to you, vary the LTV Ratio requirements (including the LTV Ratio) for any Futures Account at any time and by any level, and may also stipulate that such requirements shall apply to existing positions as well as new positions in the Transactions affected by such change. Any written notice from Hasla stating that any such circumstance has arisen shall be deemed to be a conclusive determination of that event. You acknowledge that Hasla may, in certain market conditions, effect an immediate change in LTV Ratio requirements and/or require additional Collateral to be deposited immediately or within a specified period of time which may be less than 24 hours, and waives any right to object on the grounds that such requirement is unreasonable. No previous margin requirements shall set a precedent or bind Hasla.</p>
                    <p>6.7. If Hasla determines that additional Collateral is required, you shall deposit with Hasla such additional Collateral immediately upon demand, provided that, notwithstanding any such demand for additional Margin, Hasla may at any time exercise its rights under Clause 8 (Default and Termination). In making such determination in respect of the Collateral provided for any Futures Account, Hasla shall not be required to take into consideration Collateral held by Hasla for you in respect of any other Futures Account.</p>
                    <p>6.8. You acknowledge that Collateral may be held and used to secure the performance of your obligations as well as for such other purposes as the Applicable Laws may permit or stipulate for the Transactions traded.</p>
                    <p>6.9. All Collateral shall be held by Hasla , notwithstanding any provision or instructions to the contrary, as continuing security and shall be subject to a general lien and right of set off in favour of Hasla for any and all of your obligations, liabilities or monies whatsoever at any time now or hereafter owing, due, incurred or payable by you to Hasla under this Agreement or otherwise, whether present or future, actual or contingent, solely or jointly or whether as principal or surety, and Hasla may realise any of your Collateral as provided for in this Agreement.</p>
                    <p>6.10. Hasla shall be entitled to deposit, pledge, repledge, hypothecate, re-hypothecate, invest or loan any Collateral in whatever form provided by Hasla or otherwise, and shall not be under any obligation to notify you of the same nor account to you for any interest, income or benefit that may be derived therefrom. No interest shall be paid on any type of Collateral deposited by you with Hasla and you acknowledge and agree that interest earned on the Collateral deposited under this Agreement may be retained by Hasla for its own account and benefit. Hasla shall at no time be required to deliver to you the identical property delivered to or purchased by Hasla as Collateral for the Futures Account(s) but only property of substantially the same kind and amount, subject to adjustments for quantity and quality variations at the market price prevailing at the time of such delivery. Binance shall not be liable to you for the loss of any Collateral resulting directly or indirectly from the closure, bankruptcy, insolvency, liquidation, receivership or other events of a similar nature of any broker, market association, or body with which the Collateral is deposited or pledged.</p>
                    <p>6.11. You shall at your own cost and at Hasla ’s request, execute and do all such deeds, acts and things (including without limitation, the performance of such further acts or the execution and delivery of any additional instruments or documents) as Hasla may require for the purposes of this Agreement, including but not limited to perfecting Hasla ’s rights to the Collateral provided by you.</p>
                    <p>6.12. Hasla may deposit in Hasla ’s general account or any other account, any of your Collateral and may commingle such Collateral with the Digital Currency, Digital Assets, currencies and properties of Hasla or of some other person(s).</p>
                    <p>6.13. All Collateral shall be held subject to Hasla ’s general rights in respect of your Digital Currencies and Digital Assets.</p>
                    <p>Cross Collateral Loan</p>
                    <p>6.14. Subject to the terms of this Agreement, Hasla agrees to provide to you, and you may obtain from and return to Hasla from time to time, Digital Assets and Digital Currencies to support your Transactions (each such provision of Digital Assets and Digital Currencies, a “Cross Collateral Loan”). No Cross Collateral Loan shall occur unless you meet or exceed any minimum balance requirements imposed by Hasla (if any) for your Futures Account.</p>
                    <p>6.15. Hasla shall have the right to reduce, cancel or vary and from time to time review a Cross Collateral Loan and nothing in this Agreement shall be deemed to impose on Hasla any obligation at law or in equity to make or continue to make available to you a Cross Collateral Loan.</p>
                    <p>6.16. If granted, a Cross Collateral Loan shall only be used by you for financing a Transaction provided always that you shall satisfy the required LTV Ratio as prescribed by Binance from time to time in the applicable Futures Trading Rules.</p>
                    <p>LTV Ratio And Margin Call</p>
                    <p>6.17. You agree to maintain in your Futures Account, at all times during the term of the Cross Collateral Loan, a specified minimum amount of Digital Assets and Digital Currencies approved by Hasla to qualify as Collateral for the purpose of satisfying the required LTV Ratio as prescribed by Hasla from time to time.</p>
                    <p>6.18. If at any time your Futures Account does not contain the amount of Collateral required to meet the necessary LTV Ratio requirements as prescribed by Hasla (including the necessary LTV Ratio), you agree to transfer additional Collateral to your Futures Account whether or not a Margin Call has been made by Hasla to satisfy such margin requirements.</p>
                    <p>6.19. You acknowledge that if the LTV Ratio falls below the Liquidation Level, Hasla may and shall be fully entitled (but shall not be obliged) to sell or dispose of any or all Collateral in the applicable Futures Account(s) in order to satisfy the LTV Ratio prescribed by Hasla for compliance by you, whether or not a Margin Call has been made (the “Cross Collateral Liquidation”), and Hasla is not required to provide notice before commencing the Cross Collateral Liquidation.</p>
                    <p>6.20. You give Hasla the authority and discretion to sell or dispose of any or all Collateral in any manner as stated in Clause 6.19 above.</p>
                    <p>6.21. You further acknowledge and agree that (i) you shall be liable for all commission and transaction costs relating to the Cross Collateral Liquidation, (ii) you shall be liable for any losses resulting from the Liquidation, and (iii) Hasla shall not be liable for any losses resulting from the Cross Collateral Liquidation should Binance exercise any or all of its rights under this Clause 6.</p>
                    <p>6.22. Failure of Binance to exercise any or all of its rights under this Clause 6 shall not constitute a waiver of its rights to do so at any time thereafter, nor shall Hasla be subject to any liability to you for its acts or its failure to so act.</p>
                    <p>6.23. You acknowledge and agree that it is your sole responsibility to monitor the LTV Ratio requirements (including LTV Ratio) in and for your Futures Accounts. All open positions of your Futures Accounts shall be marked-to-market daily, or at more frequent intervals as Hasla may determine in its sole and absolute discretion.</p>
                    <p>6.24. Any Margin Call made by Hasla must be met by you by transferring additional Collateral from your Hasla Account(s).</p>
                    <p>6.25. You acknowledge and agree that Hasla may (but shall not be obliged to) make Margin Calls on you in respect of any of your Futures Account orally or in writing or in such other manner as Hasla may in its sole and absolute discretion deem appropriate. Without prejudice to the generality of the foregoing, you acknowledge and agree that Hasla may contact you via telephone or email at any of the telephone number or email address provided by you to Binance for the purposes of any Margin Calls and you shall make yourself available at such telephone numbers or email. If Binance fails to reach you at any such telephone numbers or email, you shall be deemed to have defaulted on the Margin Call and Hasla may at any time exercise its rights set out in Clause 8 (Default and Termination). For the avoidance of doubt, Hasla shall be entitled (but not obliged) to make Margin Calls on you in respect of any of your Futures Account.</p>
                    <p>6.26. You acknowledge and agree that if the sale or disposal of the Collateral as stated in Clause 6.19 is insufficient to repay the Cross Collateral Loan and any accrued interest thereof, you shall be liable for any shortfall of Digital Assets owed by you to Hasla.</p>
                    <p>6.27. As Digital Asset markets are open 24 hours a day, 7 days a week, Margin Calls in respect of Cross Collateral Loans and liquidations may occur at any time, including outside of normal business hours. You further agree and acknowledge that the prices of Digital Assets are volatile and thus may decline speedily in value.</p>
                    <p>Repayment of Cross Collateral Loan</p>
                    <p>6.28. You shall repay any Cross Collateral Loan by selling some or all of the Digital Assets in your Futures Account. To the extent permitted under Applicable Laws, Hasla may, in its sole and absolute discretion, apply the proceeds from the sale of any Digital Assets in your Futures Account, first to the payment of any interest then due, then to any outstanding fees, commissions, charges or other expenses then due to Hasla , and then to the payment of any principal amount outstanding on the Cross Collateral Loans. You agree and acknowledge that only after all outstanding Cross Collateral Loans are repaid would the sale of a Digital Asset or incoming transfer of USD result in a positive balance of USD in the Futures Account.</p>
                    <p>6.29. You acknowledge and agree that the longer the term of the Cross Collateral Loan, the higher the accrued interests and related fees, commission and/or charges that Hasla may charge to you in respect of such Cross Collateral Loan.</p>
                    <h3>7. Fees, Interest, Commissions and Charges</h3>
                    <p>7.1. You shall promptly pay all of Hasla ’s fees, interest, commissions and/or other charges at such rates and in such manner as Hasla may impose and stipulate from time to time with respect to the execution and/or performance of any Transaction or otherwise for the maintenance of any Futures Account or the provision of any service or Cross Collateral Loan to you or in connection with any Futures Account. Hasla reserves the right from time to time in its sole and absolute discretion and by notice to you to vary the rates of fees, interest, commissions and charges or impose other fees, interest, commissions and charges. Fees, interest, commissions and other charges may be quoted on requested, posted on Hasla ’s website or mobile application or individually notified via post or other modes of communication as Hasla in its sole and absolute discretion may deem fit. It is your responsibility to ensure that you are aware of current applicable fees, interest, commission, charges and rates.</p>
                    <p>7.2. You shall make payment to Hasla promptly of any outstanding sum (including without limitation any outstanding fees, interest, commissions and charges) in respect of any Transaction on the due date of the relevant Transaction or upon demand by Hasla.</p>
                    <p>7.3. All commissions, interest, fees, charges or sums to be payable from you to Hasla may be settled by Hasla at its sole and absolute discretion on the day they fall due by debiting your Hasla Account (including your Futures Account) with the relevant amount payable by you. In the event that there are insufficient Digital Assets in your Hasla Account (including your Futures Account), you acknowledge that any amount due and payable from you under this clause is a debt immediately due and owing by you to Hasla.</p>
                    <p>7.4. Subject to Clause 7.5, interest charged on any Cross Collateral Loan shall be at the interest rates prescribed on the Futures Trading Rules (in particular the cross collateral interest rate at www.binance.com/en/fee/FuturesLoanRate (“Interest Rates”). If at any time and for any reason whatsoever, the Interest Rates made under this Agreement exceed the maximum rate of interest permitted to be charged by Hasla to you under Applicable Laws, you and Hasla agree that such Interest Rates will be reduced automatically to the maximum rate of interest permitted to be charged under Applicable Law.</p>
                    <p>7.5. Hasla shall be entitled at its sole and absolute discretion to charge interest on any sum or payment due to Hasla from you (including any Cross Collateral Loans) at such rate and calculated and/or compounded in such manner as Hasla may impose and determine from time to time and to debit any Hasla Account (including any Futures Account) in respect of the interest due.</p>
                    <p>7.6. All payments to Hasla shall be in the Digital Currency or Digital Assets as solely determined by Hasla and free of deduction or withholdings (if applicable). If you are required to effect such deductions or withholdings, then the amount due to Hasla shall be increased by such amount as shall result in Hasla receiving an amount equal to the amount Hasla should have received in the absence of such deduction or withholding.</p>
                    <p>7.7. Any applicable taxes, duties, disbursements, costs and/or other expenses incurred by Hasla in connection with you or your Futures Account shall be reimbursed by you.</p>
                    <p>7.8. If for any reason Hasla cannot effect payment or repayment to you in a particular Digital Currency or Digital Assets in which payment or repayment is due, Hasla may effect payment or repayment in the equivalent in any other Digital Currency or Digital Assets selected by Hasla based on a rate of exchange solely determined by Hasla in respect thereof at the relevant time.</p>
                    <p>7.9. All interest, fees, commissions and other charges of Hasla are exclusive of any goods and services tax or any other applicable sales tax which shall be borne and separately charged to you.</p>
                    <h3>8. Default and Termination</h3>
                    <p>8.1. A “Default” shall be deemed to occur if:</p>
                    <p>(a) your Maintenance Margin or LTV Ratio in your Futures Account falls below the margin requirements and LTV Ratio requirements as respectively prescribed by Hasla in the applicable Futures Trading Rules;</p>
                    <p>(b) any representation, warranty, agreement or undertaking made by you to Hasla (whether under or in connection with this Agreement (including without limitation Clause 10 (Your Representations, Warranties, Agreement and Undertakings)), the Futures Trading Rules, the Terms of Use or otherwise) or any other material statement made by you in or in connection with the same being untrue, inaccurate, incomplete or misleading in any respect at the time when made by you or thereafter at any time becomes untrue, inaccurate, incomplete or misleading in any respect and you fail to inform Hasla of the true position as soon as reasonably practicable;</p>
                    <p>(c) you have failed to comply with or perform any of your obligations hereunder or in respect of any Futures Account or Transaction or under this Agreement, the Futures Trading Rules, or the Terms of Use (including without limitation your failure to make, when due, any payment or delivery required to be made by you under this Agreement, the Hasla Platform Rules or the Terms of Use or in respect of any Futures Account or Transaction) or has breached or is being investigated by the relevant authorities for breaching any Applicable Laws;</p>
                    <p>(d) you fail to promptly provide Hasla with verification of your identity or status or the identity or status empowered by you to act on your behalf or information and/or documents in relation to credit checks and assessments conducted by Hasla;</p>
                    <p>(e) (in the event that you are an individual), you shall become deceased, bankrupt, of unsound mind or insane, commit an act of bankruptcy, or have action to place you in bankruptcy commenced against you;</p>
                    <p>(f) (in the event that you are acting on behalf of a partnership) any of the partners thereof shall become deceased, bankrupt or insane, commit an act of bankruptcy, or have action to place any of the partners in bankruptcy commenced, or if action is commenced to dissolve and/or alter the partners or the constitutions of the partnership;</p>
                    <p>(g) (in the event that you are acting on behalf of a corporation) the corporation shall be unable to pay its debts as and when they are due, or action is commenced to place the corporation in insolvency, judicial management, receivership, administrative management, or any similar or analogous proceedings;</p>
                    <p>(h) any investigation, claim, action or proceeding of any nature is commenced against you (including without limitation investigation into suspected market abuse, manipulation or other criminal conduct), or steps are taken by any person to enforce any security against you;</p>
                    <p>(i) you convene a meeting of your creditors or propose or make any compromise or arrangement with or any assignment for the benefit of your creditors;</p>
                    <p>(j) Hasla has reasonable concerns in relation to your creditworthiness, financial status or verification of your identity;</p>
                    <p>(k) Hasla determines in its sole and absolute discretion that you have acted in an abusive manner to any representative of Hasla;</p>
                    <p>(l) unless alternative arrangements have been made between you and Hasla with reference to a specific absence by you, at any time Hasla is not able to contact you within 24 hours using reasonable means and contact points known to Hasla;</p>
                    <p>(m) Hasla forms the view, in good faith, that it should take action in order to preserve its rights or interests under any Hasla Account or Futures Account or under its relationship with you;</p>
                    <p>(n) Hasla reasonably believes that any of the circumstances set out under Clauses 8.1(a) to 8.1(m) above are likely to happen and Hasla also reasonably believes that any action described in Clause 8.2 below is necessary, desirable or expedient to protect its interests or the interests of Hasla ’s other clients; or</p>
                    <p>(o) a credible allegation of fraud, misconduct, embezzlement, money laundering, insider trading, market manipulation abuse or other material illegality, breach of regulation or impropriety is made against you, that in the good faith and commercially reasonable business judgment of Hasla could reasonably result in reputational harm to Hasla, or compromise the integrity of the markets maintained by Hasla .</p>
                    <p>8.2. Without prejudice to any other right of Hasla hereunder or otherwise at law, in the event of Default, Hasla may (but is not obliged to) immediately or any time thereafter, do any one or more of the following:</p>
                    <p>(a) suspend(indefinitely or otherwise)cancel or terminate any Hasla Account,Futures Account,or Hasla ’s relationship with you or prohibit you from opening any Hasla Account and/or Futures Account and accelerate any and all of your liabilities to Hasla (including any and all of your Cross Collateral Loans, fees, interests, commission, and charges owed by you to Hasla ) so that they shall become immediately due and payable;</p>
                    <p>(b) liquidate, accelerate, hedge and/or close out any outstanding Transaction (including any Transaction which has yet to be settled on the date on which Hasla terminates such Transaction) by determining its value in good faith and in its absolute discretion as of the date of the close-out as soon as practicable after the close-out;</p>
                    <p>(c) at such times and manner as Hasla may reasonably determine based on, but not limited to, market conditions and portfolio health, sell or otherwise transfer any Digital Assets or other property which Hasla may hold for you or which has been pledged to Hasla by you and apply the proceeds to the discharge of your obligations, set-off, net and recoup any obligations to you against any obligations to Hasla;</p>
                    <p>(d) vary the applicable margin requirement or LTV Ratio requirements or liquidate or exercise its power to sell the Margin or Collateral or part thereof at a price which Binance deems appropriate in the circumstances;</p>
                    <p>(e) apply any amounts of whatsoever nature standing to your credit against any amounts which you owe Binance (of whatsoever nature and howsoever arising, including any contingent amounts), or generally to exercise Hasla ’s rights of netting or set-off against you under this Agreement, the Terms of Use, Applicable Laws or otherwise;</p>
                    <p>(f) demand any shortfall after Clause 8.2(e) above from you, or hold any excess pending full settlement of any other of your obligations, or pay any excess to you by way of any methods deemed appropriate by Hasla;</p>
                    <p>(g) do or omit to do anything which Hasla reasonably believes to be necessary, desirable or expedient to protect Hasla or its other clients; and/or</p>
                    <p>(h) exercise such other authority and powers that may have been conferred upon Hasla by this Agreement, the Hasla Platform Rules and/or the Terms of Use.</p>
                    <p>8.3. To the extent permitted under Applicable Law, you will be responsible for the reasonable costs and expenses of collection of any unpaid deficiency in your Futures Account including, but not limited to, legal counsel’s fees incurred and payable or paid by you.</p>
                    <h3>9. Statements, Confirmations</h3>
                    <p>9.1. You shall verify all statements and Confirmations of Transactions done and Futures Account(s) status sent by Hasla to you from time to time. If no objection is raised within 7 days of the date of the statement, Confirmation or advice of Transactions done (or such other time period set out in the said statement, Confirmation or advice), such statement, Confirmation or advice shall be deemed conclusive and binding as against you, and you shall not be entitled to object thereto. However, Hasla may at any time rectify any error on any entry, statement, Confirmation or advice which has been proved to its satisfaction, and may demand immediate repayment from you of any Digital Assets and/or Digital Currencies erroneously paid over to you as a result of such error. Any and all objections by you shall not be valid unless accompanied by supporting evidence for such objections.</p>
                    <p>9.2. You shall immediately notify Hasla if a statement, Confirmation or advice is not received by you in the ordinary course of business or your use of Hasla ’s services.</p>
                    <p>9.3. Subject to the provisions of this Clause, a Confirmation which does not accurately reflect the relevant Transaction entered into via the relevant Electronic Facility:</p>
                    <p>(a) does not affect the validity of the Transaction which the Confirmation evidences; and</p>
                    <p>(b) where there is Manifest Error, does not entitle you to enforce whatever is inaccurately recorded in the Confirmation.</p>
                    <p>9.4. Hasla reserves the right to void or reverse from the outset any Transaction involving or deriving from a Manifest Error or to amend the details of such Transaction to reflect that which Hasla considers in its sole and absolute discretion acting in good faith to be the correct or fair details of such a Transaction absent Manifest Error.</p>
                    <p>9.5. Without prejudice to the generality of the other terms in this Agreement, and in the absence of fraud or bad faith, Hasla shall in no circumstances be liable to you for any Loss or demand of whatsoever nature you may suffer or incur in connection with any Manifest Error howsoever arising, whether direct or indirect, special or consequential, including, but not limited to, loss of profit, loss of opportunity or even if Hasla had been advised of the possibility of the same arising or that the same were reasonably foreseeable. Your attention is drawn in particular to Clause 12 (General Exclusion) of this Agreement.</p>
                    <h3>10. Your Representations, Warranties, Agreement and Undertakings</h3>
                    <p>10.1. You represent, warrant, agree and undertake that:</p>
                    <p>(a) you have full capacity and authority to accept and agree to the terms of this Agreement, to open, maintain and/or continue to maintain all Futures Account(s) from time to time opened and/or maintained and/or continued to be maintained with Binance, and to give Hasla Orders thereon;</p>
                    <p>(b) you have received, read and understands and accept that the level(s) of services available to you are as described on the Futures Trading Rules including cross margin mode and isolated margin mode; will vary depending on whether you are transacting or intending to transact on cross margin mode or isolated margin mode. You further and specifically confirm that you have read and understood each of the applicable Futures Trading Rules; and accept the conditions and limitations for each and every service available to you in connection with the Futures Trading Rules;</p>
                    <p>(c) you have all authorisations, consents, licences or approvals (whether under Applicable Laws or otherwise) required to accept and agree to these terms and conditions, to open, maintain and/or continue to maintain all Futures Account(s) from time to time opened and/or maintained and/or continued to be maintained with Hasla , and to give Binance Orders thereon;</p>
                    <p>(d) you are not an employee of any governmental or self-regulatory organisation in any jurisdiction, including any exchange or a member firm thereof, or engaged in the business of dealing (either as agent or principal), which prohibits you from establishing a relationship with Hasla in dealing in any of the Digital Currency and/or Digital Assets traded under the Futures Account(s), and you shall promptly notify Binance if you become so employed;</p>
                    <p>(e) you do not reside in the prohibited countries and territories as per set out in Terms of Use, or any other jurisdictions which residents Hasla deems from time to time to be prohibited from using the services provided under this Agreement;</p>
                    <p>(f) unless you specifically notify Hasla and Hasla agreed, no person other than you has an interest in any Futures Account;</p>
                    <p>(g) except with the express written consent of Hasla , and except for any security or encumbrance created hereunder, no person has or will have any security or other encumbrance over any Futures Account and/or any cash or property in any Futures Account;</p>
                    <p>(h) any Order, placed or any other dealings in the Futures Account(s) is solely and exclusively based on your own judgment and after your own independent appraisal and investigation into the risk associated with such Orders and your own independent determination of the Order being specifically suitable for you based on your own assessment of your financial resources, ability and willingness to take relevant risks and financial objectives;</p>
                    <p>(i) Hasla shall not be under any duty or obligation to inquire into the purpose or propriety of any Order and shall be under no obligation to see to the application of any funds delivered by you in respect of any Futures Account;</p>
                    <p>(j) any person(s) empowered to act on your behalf have been duly authorised;</p>
                    <p>(k) you have complied and shall comply with all Applicable Laws in all jurisdictions relevant to any Futures Account, Transaction or service or facility provided or made available by Hasla to you;</p>
                    <p>(l) all information and/or documents provided by or for or to be provided by or for you to Hasla in relation to any application or pursuant to or under this Agreement are true, accurate, complete and not misleading in any and all respects, and nothing has been concealed from Hasla which may have a material bearing on Hasla ’s decision to provide or continue to provide any of the services under this Agreement; and</p>
                    <p>(m) you shall not knowingly or recklessly permit the use of Hasla ’s services, facilities or membership in a manner which is in the opinion of Hasla liable to bring Hasla into disrepute, impair the dignity or degrade the good name of any of the foregoing. You shall not knowingly or recklessly create or maintain or exacerbate manipulations (or attempted manipulations), corners (or attempted corners) or violation of any Applicable Laws (or arrangements, provisions or directions made or given thereunder), or otherwise be substantially detrimental to the interests or welfare of Hasla.</p>
                    <p>10.2. The above representations, warranties, agreement and undertakings shall be deemed repeated whenever you give Orders to Hasla , enter into any Transactions or establish a new Futures Account with Hasla.</p>
                    <h3>11. General Indemnity</h3>
                    <p>11.1. In addition and without prejudice to any other right or remedy of Hasla (at law or otherwise) you shall at all times indemnify, keep indemnified, and hold Hasla harmless from and against any and all Loss suffered or incurred by Hasla which arises (whether directly or indirectly) out of, in the course of or in connection with:</p>
                    <p>(a) any Default or any failure by you to comply with any of these terms and conditions or Applicable Laws;</p>
                    <p>(b) Hasla acting in accordance with your orders or in any manner permitted under this Agreement and/or the Terms of Use;</p>
                    <p>(c) any changes in any Applicable Laws; and/or</p>
                    <p>(d) any act or thing done or caused to be done by Hasla in connection with or referable to this Agreement, the Terms of Use or any Futures Account.</p>
                    <p>11.2. You shall further indemnify, keep indemnified and hold harmless Hasla for any and all expenses, costs and legal fees (on a full indemnity basis) incurred, including but not limited to expenses, costs and legal fees incurred for producing records, and information, or payment made (whether such payment is or was or is to be made in settlement of any proceedings or in connection with any ruling, judgment, order or award) by any of them in connection with any investigations or proceedings (whether legal, regulatory, arbitration or other proceedings) brought against it in connection with Clauses 11.1(a) to 11.1(d) above. You shall provide any and all assistance to Hasla in connection with such investigations or proceedings.</p>
                    <h3>12. General Exclusion</h3>
                    <p>12.1. Futures trading is not suitable for everyone. You should examine your investment objectives, financial resources and risk tolerance to determine whether borrowing against your assets held with Hasla is appropriate for you. You acknowledge that margin trading is a highly speculative activity involving highly leveraged and rapidly fluctuating markets. You further understand and accept the significant risks associated with the use of margin or loan and the use of margin or loan is consistent with your investment objectives. Despite such risks, you acknowledge, understand and agree that you are willing and able to assume the financial risks and other hazards of margin trading and agree that you will in no manner hold Hasla responsible for Losses incurred by you under or in connection with this Agreement, the Futures Trading Rules and the Terms of Use.</p>
                    <p>12.2. In addition and without prejudice to any other right or remedy which Hasla may have (under this Agreement, the Terms of Use, at law or otherwise) so long as Hasla acts in good faith, it shall not be liable to you in any respect for any Loss suffered by you, including, without limitation, any Loss resulting from default, insolvency or analogous proceedings of, or action or inaction by any intermediary (including wrongful or unlawful action or inaction) or howsoever otherwise suffered and/or incurred by you under or in connection with this Agreement, the Futures Trading Rules and the Terms of Use. Hasla shall only be liable to you if Hasla has been fraudulent or in wilful default.</p>
                    <p>12.3. Without prejudice to the generality of the foregoing, Hasla shall not in any event be liable to you for any indirect or consequential Loss, or for any anticipated profits or punitive damages.</p>
                    <h3>13. Applicable Laws</h3>
                    <p>13.1. Your relationship with Hasla , the operation of any Futures Accounts and the implementation of any Transaction shall be subject at all times to the Applicable Laws. Hasla may take or refrain from taking any action whatsoever, and you shall comply with, and shall do all things required by Hasla in order to procure or ensure compliance with, Applicable Laws. You agree that Hasla shall not be liable to you as a result of any action taken by Hasla to comply with Applicable Laws.</p>
                    <h3>14. Technology Disclaimer</h3>
                    <p>14.1. For the purpose of the Transactions, Hasla may offer or make available for your access and use of the Electronic Facilities comprising of such trading systems, platforms and/or related software and technology (the “Trading Systems”) to enable, assist and/or facilitate you to place Orders, enter into and/or settle Transactions. These Trading Systems may be proprietary to Hasla or may be licensed by Hasla from third party licensors (the “Third Party Licensors”) for access and/or use by you. In addition to the terms of this Agreement, you agree and undertake to comply with any and all terms and conditions as Binance and/or such Third Party Licensors may from time to time prescribe or stipulate to be applicable to their provision and/or your access and/or use of such Trading Systems.</p>
                    <p>14.2. You acknowledge and agree that access and use of the Electronic Facilities is provided on an “as is” and “as available” basis and Hasla makes no representation or warranty of any kind, express or implied, with respect to the functionality, operation, content or otherwise of the Electronic Facilities and does not represent or warrant that the Electronic Facilities or any part thereof is free from defect, failure or interruption or that they are fit for your purposes or any particular purpose and, without prejudice to the foregoing, Hasla shall not in any event be liable for any system error, faults or failure of the Electronic Facilities whatsoever and howsoever arising or caused other than by fraud or wilful default of Hasla.</p>
                    <p>14.3. To the extent that you may use third party technology, web applications, application programme interfaces, software, software code, programmes, protocols and/or other third party resources (the “Third Party Applications”) whether independently identified and selected, sourced or used by you, made available via Hasla or otherwise, to provide connectivity to the Electronic Facilities offered or made available by Hasla to place Orders, enter into and/or settle Transactions, you acknowledge and accept that you are solely responsible for and will bear all risks that such Third Party Applications may not be compatible with or function appropriately with the Electronic Facilities.</p>
                    <p>14.4. Hasla disclaims and excludes unless expressly prohibited by applicable mandatory law, all terms and conditions and warranties implied by statute or common law in relation to the Electronic Facilities including, but not limited to, merchantability, satisfactory quality, suitability or fitness for any particular purpose. Technical difficulties may be encountered in connection with the Electronic Facilities. Such difficulties may include, but not be limited to, malfunctions, failures, delays, hardware damages or software erosion. Such difficulties could be the result of hardware, software or communication link inadequacies or any other cause and such difficulties could lead to possible economic and/or data loss. In the absence of fraud or wilful default, in no event will Hasla , any of its related companies or affiliates or any of their respective officers, employees, agents, representatives or contractors be liable for any loss, cost, claim, demand, expense or damage including, without limitation, loss of profit, loss of revenue, loss of opportunity, consequential, unforeseeable, special or indirect damages or expenses which arise directly or indirectly as a result of accessing or using the Electronic Facilities, even if Hasla had been advised of the possibility of the same arising or that the same were reasonably foreseeable.</p>
                    <p>14.5. Hasla may use or provide technology and/or electronic services, or make available technology and/or electronic services provided by third parties, for your use in connection with any Order placed or Transaction made by you with Hasla . Such technology and electronic services may include, but is not limited to, trading technology, web applications, application programme interfaces, software, software code, programmes, protocols and displays (collectively, the “Technology”) for trading, analysing trades and markets, constructing automated trading systems and/or to assist or facilitate the provision, availability or connectivity of Electronic Facilities provided or made available by Hasla to you for access or use. Hasla provides the Technology “as is”, without any warranties of merchantability, fitness for a particular purpose, or other express or implied warranties. You acknowledge and agree that none of Hasla , any Third Party Licensors and any other third party Technology providers shall be responsible for the operation or performance of any automated trading system developed with Technology or for any errors, malfunctions or breakdown of, or inability to access, any Technology or Electronic Facilities or for any delays or interruptions in transmission of orders due to breakdown, excessive call volume or failure of transmission or communication equipment on the internet or otherwise, including, but not limited to, communications problems, computer software or hardware breakdowns, malfunctioning errors, any and all problems or glitches associated with computer problems or any other technical cause or causes.</p>
                    <p>14.6. You acknowledges that certain databases, programmes, protocols, displays and manuals which may form part of the Technology (the “Proprietary Information”) are proprietary and unique to Binance, Third Party Licensors or third party Technology providers, as to which copyright, patent, or other proprietary rights may be held by Hasla , such Third Party Licensors, third party Technology providers or third parties from whom such Third Party Licensors or third party Technology providers have licensed or otherwise acquired such rights. You agree to take or cause to be taken any and all necessary precautions to maintain the confidentiality of such Proprietary Information, to comply with all copyright, trademark, trade secret, patent and other laws necessary to protect all rights in the Proprietary Information as advised by Hasla and agrees not to remove, conceal or obliterate any copyright or other proprietary notice, which may include references to Hasla , such Third Party Licensors or such other third parties’ ownership, as included in the Technology.</p>
                    <p>14.7. You acknowledge, accept and agree that Binance, any Third Party Licensors or any other third party Technology providers and their respective directors, officers, employees, agents, contractors and/or sub-contractors shall not be held liable for any loss, damage, cost or expense (including the loss of data) suffered or incurred by you as a result, arising out of or in connection with any errors, malfunctions, breakdowns, inability to access, faults, interruptions or delays in the Technology, or Electronic Facilities or out of any inaccuracies, errors or omissions in the information contained in the Technology or Trading Systems as supplied to, or made available for access and use by, you, provided however that this limitation does not apply to any loss, cost or damage suffered or incurred by you caused by fraud or wilful default of Hasla in the performance of its duties imposed by this Agreement or applicable law. Each of Hasla , such Third Party Licensors and such third party Technology providers makes no warranties, conditions, guarantees or representations as to satisfactory quality, fitness for a particular purpose or other warranties, conditions, guarantees or representations, whether express or implied, in law or in fact, oral or in writing, except as expressly stated in the terms of this Agreement. Under no circumstances shall Hasla , such Third Party Licensors and/or such third party Technology providers be liable for any loss, damage, cost or expense of any nature whatsoever incurred or suffered by you of an indirect, incidental, special or consequential nature (including without limitation any economic loss or other loss of turnover, profits, business or goodwill) arising from or in connection with the provision of, or the availability to you of, any Technology or Electronic Facilities.</p>
                    <p>14.8. Without prejudice to the generality of the foregoing, you agree not to bring any legal action, whether in tort, contract or otherwise, against Hasla , any Third Party Licensors or any other third party Technology providers alleging damages for, the failure by Hasla to perform or otherwise settle a Transaction entered by you using Technology.</p>
                    <p>14.9. Use of the Futures service may require compatible hardwares or devices, internet access, web browser that includes 128-bit encryption (e.g. Chrome/Edge/Firefox/Safari/Opera, latest version recommended and require periodic updates) and Hasla software (latest version recommended and requires periodic updates). Futures services’ performance may be affected by the performance of these factors. It is not recommended to operate Futures with a touchscreen device on a web browser. You agree that meeting these requirements is your responsibility. Hasla shall not be liable for any losses resulting directly or indirectly from the incompatible hardwares or devices, personal network congestion, network delay, poor network environment and outdated version of software. Hasla reserves the right to limit the number of Futures Accounts that may be created from a device and the number of devices associated with a Futures Account.</p>
                    <h3>15. Miscellaneous</h3>
                    <p>15.1. The provisions of Clause X (Resolving Disputes: Forum, Arbitration, Class Action Waiver) of the Terms of Use shall apply mutatis mutandis as if set out in this Agreement.</p>
                    <p>15.2. This Agreement is drafted in the English and Chinese language. In the event that there are inconsistencies between the English version of this Agreement and the Chinese version of this Agreement, the English version shall prevail.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!--End of privacy policy -->
<?php include 'inc/footer.php'; ?>